import type { NextPage } from 'next'
import Head from 'next/head'
import Avatar from '../components/Avatar'
import Footer from '../components/Footer'
import { ViewGridIcon,MicrophoneIcon  } from '@heroicons/react/solid'
import { SearchIcon  } from '@heroicons/react/outline'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { FormEvent, useState } from 'react'

const Home: NextPage = () => {
  const [input, setInput] = useState("")
  const router = useRouter();
  const handleSearch = (e:FormEvent<HTMLFormElement>) =>{
    e.preventDefault();
    router.push(`/search?term=${input}&start=0`)
  }
  return (
    <div className='flex flex-col items-center h-screen justify-between'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex justify-between p-4 w-full text-sm text-gray-700'>
          <div className='flex space-x-4 items-center'>
            <p className='link'>About</p>
            <p className='link'>Store</p>
          </div>
          <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
            <p className='link'>Images</p>
            <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>
            <Avatar img ="https://www.pinpng.com/pngs/m/341-3415688_no-avatar-png-transparent-png.png"/>
          </div>
      </header>
      <form className='flex flex-col items-center w-4/5' onSubmit={handleSearch}>
        <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1920px-Google_2015_logo.svg.png" alt="Google" width={300} height={100} />
        <div className='flex  w-full max-w-md items-center border-gray-300 border-[1px] space-x-1 px-2 rounded-full p-2 hover:shadow-lg focus-within:shadow-lg sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='h-5 w-5 text-gray-500'/>
          <input type="text" className='flex-grow outline-none ' onChange={(e)=>setInput(e.target.value)}/>
          <MicrophoneIcon className='h-5 w-5 text-gray-500'/>
        </div>
        <div className='space-x-2  flex flex-col  sm:flex-row  justify-center items-center my-2'>
          <button className='btn mb-2 sm:mb-0' >Google Search</button>
          <button className='btn'>I'm feeling Lucky</button>
        </div>
      </form>
      <Footer/>
    </div>
  )
}

export default Home
